
from flask import Flask, render_template, request, jsonify

from chat import get_response

app = Flask(__name__)

@app.get("/")
def index_get():
    """
    Renders the base.html template for the index page.

    Returns:
        The rendered HTML template.
    """
    return render_template("base.html")

@app.post('/predict')
def predict():
    """
    Handles the POST request to the '/predict' endpoint.

    Returns:
        A JSON response containing the answer generated by the chatbot.
    """
    text = request.get_json().get("message")
    response = get_response(text)
    message = {"answer": response}
    return jsonify(message)

if __name__ == "__main__":
    app.run(debug=True)